// apps/frontend/src/App.svelte
<script lang="ts">
  const title = "AI Support Chat";
</script>

<main class="shell">
  <section class="chat-widget" aria-label={title}>
    <header>
      <p>Spur Demo Store</p>
      <h1>{title}</h1>
    </header>

    <div class="placeholder">
      <p>The chat experience will land in the next stages.</p>
    </div>
  </section>
</main>

// apps/frontend/app/page.tsx
const title = "AI Support Chat";

export default function HomePage() {
  return (
    <main className="shell">
      <section className="chat-widget" aria-label={title}>
        <header>
          <p>Spur Demo Store</p>
          <h1>{title}</h1>
        </header>

        <div className="placeholder">
          <p>The chat experience will land in the next stages.</p>
        </div>
      </section>
    </main>
  );
}
